version = 1

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"

[[transformers]]
name = "dotnet-format"
enabled = true